package api

import (
	_ "embed"
	"encoding/json"
	"strings"
)

// The agent-facing authoring guide is generated from the SAME block palette that
// drives the editor's slash menu. Source of truth:
// frontend/src/components/app/blocks-manifest.json; the backend copy is generated
// by `make blocks-gen` (go:embed can't reach into frontend/). The blocks gate
// (`make blocks-gate`) keeps the two in sync and fails if a renderer plugin has
// no entry — so agents can never silently fall behind what the reader can render.

//go:embed blocks_gen.json
var blocksManifestJSON []byte

type blockSpec struct {
	ID       string   `json:"id"`
	Label    string   `json:"label"`
	Hint     string   `json:"hint"`
	Category string   `json:"category"`
	Slash    bool     `json:"slash"`
	Agent    bool     `json:"agent"`
	Keywords []string `json:"keywords"`
	Syntax   string   `json:"syntax"`
	When     string   `json:"when"`
	Note     string   `json:"note"`
}

var authoringBlocks, manifestDirectives, manifestCalloutTypes = loadBlocks()

// loadBlocks also returns the two name lists the generator lifts from the
// frontend's own transforms: which `:::name` directives and `> [!TYPE]` callouts
// the reader actually recognizes. The page lint needs them to tell a real block
// from one that will silently unwrap, and they must not be a second hand-written
// copy of the frontend's sets.
func loadBlocks() ([]blockSpec, []string, []string) {
	var wrap struct {
		Blocks       []blockSpec `json:"blocks"`
		Directives   []string    `json:"directives"`
		CalloutTypes []string    `json:"calloutTypes"`
	}
	// The file is embedded + generated by our own gate, so a parse failure is a
	// build/codegen bug; degrade to no blocks rather than panicking the server.
	_ = json.Unmarshal(blocksManifestJSON, &wrap)
	return wrap.Blocks, wrap.Directives, wrap.CalloutTypes
}

// Category display order for the agent guide; unlisted categories follow in
// first-seen order. Keep the high-signal, tela-specific blocks first.
var authoringCategoryOrder = []string{
	"Callouts & quotes",
	"Layout",
	"Media & diagrams",
	"Code & math",
	"Lists & tables",
	"Inline marks",
}

// agentBlocksByCategory groups the agent-relevant blocks by category in display
// order, preserving manifest order within each group.
func agentBlocksByCategory() (order []string, byCat map[string][]blockSpec) {
	byCat = map[string][]blockSpec{}
	seen := map[string]bool{}
	for _, b := range authoringBlocks {
		if !b.Agent {
			continue
		}
		if !seen[b.Category] {
			seen[b.Category] = true
		}
		byCat[b.Category] = append(byCat[b.Category], b)
	}
	for _, c := range authoringCategoryOrder {
		if _, ok := byCat[c]; ok {
			order = append(order, c)
			delete(seen, c)
		}
	}
	// Any category not in the explicit order, in manifest first-seen order.
	for _, b := range authoringBlocks {
		if b.Agent && seen[b.Category] {
			order = append(order, b.Category)
			delete(seen, b.Category)
		}
	}
	return order, byCat
}

// authoringGuideMarkdown renders the full block palette as a markdown guide. The
// examples are wrapped in 4-backtick fences so their own ``` fences (mermaid,
// code) survive verbatim. With withExample, a short worked page is appended.
func authoringGuideMarkdown(withExample bool) string {
	fence := "````"
	var b strings.Builder
	b.WriteString("# Authoring tela pages\n\n")
	b.WriteString("A tela page body is markdown, but the reader renders a rich block palette **beyond plain markdown**. Reach for these blocks to make pages scannable and visual instead of walls of text — a callout for an aside, tabs for alternatives, a real diagram over a described one. Standard markdown (headings, lists, **bold**, links, tables) works as usual.\n")

	order, byCat := agentBlocksByCategory()
	for _, cat := range order {
		b.WriteString("\n## " + cat + "\n")
		for _, blk := range byCat[cat] {
			b.WriteString("\n### " + blk.Label + "\n")
			if blk.When != "" {
				b.WriteString(blk.When + "\n")
			}
			if blk.Note != "" {
				b.WriteString(blk.Note + "\n")
			}
			b.WriteString(fence + "markdown\n" + blk.Syntax + "\n" + fence + "\n")
		}
	}

	b.WriteString("\n## Checking your work\n\n")
	b.WriteString("You can't see the reader, and several things it does are invisible in the markdown: an unrecognized `:::name` or `[!TYPE]` silently unwraps to bare text, raw HTML is dropped entirely, a `<details>` without blank lines around its body disappears whole, and a `[[Wikilink]]` to a page that doesn't exist yet renders as plain text. Re-reading what you wrote cannot catch any of these.\n\n")
	b.WriteString("- **`lint_page`** — reports exactly these divergences, with the fix.\n")
	b.WriteString("- **`preview_page`** — returns the page as the reader actually renders it, so you can compare it against what you intended. Worth doing after any edit whose result isn't obvious from the source.\n")

	if withExample {
		b.WriteString("\n## A worked example\n\n")
		b.WriteString("Notice how the blocks carry the structure — the reader gets scannable chrome instead of one long paragraph:\n\n")
		b.WriteString(fence + "markdown\n" + authoringExample + "\n" + fence + "\n")
	}
	return b.String()
}

// authoringExample is a compact page that demonstrates several rich blocks
// together, shown in the authoring-guide resource as a pattern to imitate.
const authoringExample = `# Rolling out feature flags

> [!IMPORTANT]
> Flags default to **off** in production. Flip them per-environment, never globally.

:::tabs
### Backend
Read the flag with ` + "`flags.Enabled(ctx, \"new-checkout\")`" + `.

### Frontend
Use the ` + "`useFlag(\"new-checkout\")`" + ` hook; it suspends until flags load.
:::

## Rollout flow

` + "```mermaid" + `
graph LR
  A[Off] --> B[Internal] --> C[Beta] --> D[GA]
` + "```" + `

:::quote{cite="Postmortem, 2026-03"}
Every incident we traced to a flag was a *global* flip. Scope them.
:::

See [[Feature flags runbook]] for the on-call steps.`

// authoringToolHint is the one-paragraph nudge appended to the create_page /
// update_page tool descriptions (shown at call time — the strongest signal). It
// names the rich blocks so the agent knows the palette exists, and points at the
// guide for exact syntax. Block names derive from the manifest so the hint can't
// drift from what the reader supports.
func authoringToolHint() string {
	var names []string
	for _, b := range authoringBlocks {
		if b.Agent {
			names = append(names, strings.ToLower(b.Label))
		}
	}
	return "tela renders a rich block palette beyond plain markdown — " +
		strings.Join(names, ", ") +
		". Prefer these over walls of text; read the tela://authoring-guide resource (or this server's instructions) for exact syntax. After writing, call lint_page — the reader silently drops raw HTML and unwraps unrecognized blocks, which you cannot see from the markdown."
}
