-- 0049_atlas_secrets.sql — atlas: per-space source credential store (Phase 5).
--
-- Holds the access secret a source authenticates with: a git token (private
-- clone) or a Jira API token (email + base live in meta_json). Scoped to a space
-- so a source can only reference a secret in its own space — the same blast
-- radius as the managed space itself; an instance-wide secret pool would let one
-- space's manager borrow another's credential.
--
-- atlas_sources.secret_id (migration 0048) references a row here; the executor
-- resolves it into the run's transient Source.SecretValue/SecretMeta just before
-- acquire (mirrors standalone atlas's internal/secret.ResolveSource). Deleting a
-- referenced secret nulls the FK (the source falls back to public/no-auth).
--
-- SUPERSEDED by 0050 (this table was replaced by atlas_credentials). Historical
-- note: `value` was plaintext at rest here; encryption-at-rest later landed as
-- internal/secretbox, exactly as anticipated (wrap on write / unwrap on read with
-- an instance key, no schema change).
CREATE TABLE atlas_secrets (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id   BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  kind       TEXT NOT NULL,                       -- 'git' | 'jira'
  value      TEXT NOT NULL DEFAULT '',            -- the token (write-only over the API)
  meta_json  TEXT NOT NULL DEFAULT '',            -- non-secret adornments (jira email + base_url, git username)
  created_at TEXT NOT NULL DEFAULT tela_now(),
  UNIQUE (space_id, name)
);
CREATE INDEX idx_atlas_secrets_space ON atlas_secrets(space_id);

-- atlas_sources.secret_id (added in 0048) now has a real referent. Add the FK so a
-- deleted secret detaches cleanly rather than leaving a dangling id.
ALTER TABLE atlas_sources
  ADD CONSTRAINT atlas_sources_secret_fk
  FOREIGN KEY (secret_id) REFERENCES atlas_secrets(id) ON DELETE SET NULL;
