-- 0050_atlas_projects.sql — atlas becomes a first-class Project model.
--
-- Reworks the day-1 space-centric shape (0048/0049) into the real model
-- (docs/atlas.md): owner-scoped REUSABLE credentials, first-class PROJECTS (name +
-- owner + output destination + schedule), and SOURCES re-parented onto projects.
-- A project's OUTPUT mirrors standalone atlas exactly: a space (created on first
-- run if missing) or a space → top-dir page; each source then publishes under its
-- own per-source root ("dir", named after the source) beneath that. Existing
-- rows (the day-1 prod data) are backfilled, then the obsolete columns/table drop.

-- Reusable credentials, owned by a user (personal) or an org. A source references
-- one by id; the same cred serves many sources/projects in that owner's scope.
CREATE TABLE atlas_credentials (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_kind  TEXT   NOT NULL,             -- 'user' | 'org'
  owner_id    BIGINT NOT NULL,
  name        TEXT   NOT NULL,
  kind        TEXT   NOT NULL,             -- 'git' | 'jira'
  value       TEXT   NOT NULL DEFAULT '',  -- token; write-only over the API, encrypted at rest via internal/secretbox (unprefixed rows predate it and read as plaintext)
  meta_json   TEXT   NOT NULL DEFAULT '',  -- non-secret adornments (jira email/base, git username)
  created_at  TEXT   NOT NULL DEFAULT tela_now(),
  UNIQUE (owner_kind, owner_id, name)
);
CREATE INDEX idx_atlas_credentials_owner ON atlas_credentials(owner_kind, owner_id);

-- A project: what to document, where it lands, on what schedule, who owns it.
-- output_space_id NULL until the first run materializes the space (atlas's
-- create-if-missing); output_parent_page_id is the optional top-dir within it.
CREATE TABLE atlas_projects (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  TEXT   NOT NULL,
  owner_kind            TEXT   NOT NULL,           -- 'user' | 'org'
  owner_id              BIGINT NOT NULL,
  output_space_id       BIGINT REFERENCES spaces(id) ON DELETE SET NULL,
  output_parent_page_id BIGINT REFERENCES pages(id) ON DELETE SET NULL,
  cadence               TEXT   NOT NULL DEFAULT 'daily',  -- 'hourly'|'daily'|'weekly'|'monthly'|''=off
  auto_update           INTEGER NOT NULL DEFAULT 1,
  last_refresh_at       TEXT   NOT NULL DEFAULT '',
  created_at            TEXT   NOT NULL DEFAULT tela_now()
);
CREATE INDEX idx_atlas_projects_owner ON atlas_projects(owner_kind, owner_id);

-- Re-parent sources onto projects + point creds at the owner-scoped table.
ALTER TABLE atlas_sources ADD COLUMN project_id BIGINT REFERENCES atlas_projects(id) ON DELETE CASCADE;
ALTER TABLE atlas_sources ADD COLUMN cred_id    BIGINT REFERENCES atlas_credentials(id) ON DELETE SET NULL;

-- Backfill: wrap each existing managed space into a project (owner = the space's
-- org, else its owner user; output = that space), and re-parent its sources.
DO $$
DECLARE sid BIGINT; pid BIGINT; k TEXT; oid BIGINT;
BEGIN
  FOR sid IN SELECT DISTINCT space_id FROM atlas_sources LOOP
    SELECT CASE WHEN sp.org_id IS NOT NULL THEN 'org' ELSE 'user' END,
           COALESCE(sp.org_id, (SELECT user_id FROM space_members WHERE space_id = sid AND role = 'owner' LIMIT 1), 0)
      INTO k, oid FROM spaces sp WHERE sp.id = sid;
    INSERT INTO atlas_projects (name, owner_kind, owner_id, output_space_id, cadence, auto_update)
      VALUES (COALESCE((SELECT name FROM spaces WHERE id = sid), 'Project'), k, oid, sid,
              COALESCE((SELECT cadence FROM atlas_sources WHERE space_id = sid ORDER BY id LIMIT 1), 'daily'),
              COALESCE((SELECT auto_update FROM atlas_sources WHERE space_id = sid ORDER BY id LIMIT 1), 1))
      RETURNING id INTO pid;
    UPDATE atlas_sources SET project_id = pid WHERE space_id = sid;
  END LOOP;
END $$;

-- Backfill: migrate per-space secrets (0049) into owner-scoped credentials, relink.
DO $$
DECLARE sec RECORD; cid BIGINT; k TEXT; oid BIGINT;
BEGIN
  FOR sec IN SELECT * FROM atlas_secrets LOOP
    SELECT CASE WHEN sp.org_id IS NOT NULL THEN 'org' ELSE 'user' END,
           COALESCE(sp.org_id, (SELECT user_id FROM space_members WHERE space_id = sec.space_id AND role = 'owner' LIMIT 1), 0)
      INTO k, oid FROM spaces sp WHERE sp.id = sec.space_id;
    INSERT INTO atlas_credentials (owner_kind, owner_id, name, kind, value, meta_json)
      VALUES (k, oid, sec.name, sec.kind, sec.value, sec.meta_json)
      ON CONFLICT (owner_kind, owner_id, name) DO UPDATE SET value = EXCLUDED.value
      RETURNING id INTO cid;
    UPDATE atlas_sources SET cred_id = cid WHERE secret_id = sec.id;
  END LOOP;
END $$;

-- Drop the obsolete day-1 columns/table now that everything is re-parented:
-- the destination (space/top-dir) + schedule live on the project; the per-source
-- root "dir" is derived from the source name by the publisher (not a column).
ALTER TABLE atlas_sources DROP COLUMN space_id;
ALTER TABLE atlas_sources DROP COLUMN parent_page_id;
ALTER TABLE atlas_sources DROP COLUMN secret_id;
ALTER TABLE atlas_sources DROP COLUMN cadence;
ALTER TABLE atlas_sources DROP COLUMN auto_update;
ALTER TABLE atlas_sources DROP COLUMN last_refresh_at;
DROP TABLE atlas_secrets;

CREATE INDEX idx_atlas_sources_project ON atlas_sources(project_id);
