-- 0069_space_invites.sql — pending email invitations to a SPACE. The twin of
-- 0060_org_invites: a space owner shares by email, and when no tela account owns
-- that address yet we park a token-based invite here instead of asking the
-- person to register first. The raw token lives only in the emailed link (we
-- store its hash, mirroring email_tokens + org_invites).
--
-- The invitee gets the space on accept (logged-in, matching verified email) or
-- automatically when they verify a fresh signup with the invited address
-- (applyPendingInvites, which walks org AND space invites). One pending invite
-- per (space, email). Roles match the space roles enforced by isValidRole.

CREATE TABLE space_invites (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id    BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  email       TEXT   NOT NULL,
  role        TEXT   NOT NULL DEFAULT 'viewer' CHECK (role IN ('owner','editor','viewer')),
  token_hash  TEXT   NOT NULL UNIQUE,
  invited_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at  TEXT   NOT NULL DEFAULT tela_now(),
  expires_at  TEXT   NOT NULL,
  accepted_at TEXT
);

CREATE INDEX idx_space_invites_email ON space_invites (lower(email));
CREATE INDEX idx_space_invites_space ON space_invites (space_id);

-- At most one OUTSTANDING invite per (space, email); re-inviting refreshes it.
CREATE UNIQUE INDEX uq_space_invites_pending
  ON space_invites (space_id, lower(email)) WHERE accepted_at IS NULL;
