-- Per-account quota top-ups.
--
-- Limits are data in `plans`, which makes them per-TIER: every account on a tier
-- gets exactly the same allowance, and the only ways to change one account's
-- allowance were to move it to another tier (over-grants everything) or to edit
-- the tier (changes it for everybody). Neither is a top-up.
--
-- docs/editions-and-pricing.md already commits to this shape — "overage handled
-- by purchasable credit top-ups, not a forced tier jump", with a follow-on note
-- for "a Polar one-time product + credit balance". This is that balance; the
-- admin grant is simply its first issuer, and a purchased top-up later writes the
-- same row.
--
-- ADDITIVE, not an override: a credit raises the tier's cap rather than replacing
-- it, so it composes with a later plan change instead of stranding a stale
-- absolute number. A credit against an UNLIMITED (NULL) cap is a deliberate
-- no-op — there is nothing to top up.
--
-- PERIOD-SCOPED by default, because every metric it can top up resets on the 1st.
-- '' means "every period", which is really a bespoke plan and should be rare —
-- prefer a dated grant so an exception expires by itself rather than by someone
-- remembering.
--
-- `metric` deliberately reuses the plans COLUMN NAME so the mapping between a
-- credit and the cap it raises is greppable, and a typo'd metric is a no-op
-- rather than a silent grant against the wrong meter.

CREATE TABLE account_credits (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_kind TEXT   NOT NULL CHECK (account_kind IN ('user', 'org')),
    account_id   BIGINT NOT NULL,
    -- 'YYYY-MM' for a single calendar month; '' = applies to every period.
    period       TEXT   NOT NULL DEFAULT '',
    -- A plans column name, e.g. 'max_atlas_minutes_per_month'.
    metric       TEXT   NOT NULL,
    amount       BIGINT NOT NULL,
    -- Why this account got an exception. Not optional in spirit: a grant nobody
    -- can explain later is indistinguishable from a mistake.
    reason       TEXT   NOT NULL DEFAULT '',
    granted_by   BIGINT,
    created_at   TEXT   NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_account_credits_lookup ON account_credits(account_kind, account_id, period);
